name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -la
      - name: Update version
        run: echo "VERSION = 'v${{ github.run_number }}'" > __version__.py

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/destag/literate-telegram:v${{ github.run_number }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
